spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/testdb
#    username: root
#    password: ${DATABASE_KEY_DEV}

    url: jdbc:h2:mem:test
    username: admin
    password: admin

  liquibase:
    contexts: dev
