spring:
  application:
    name: typer
  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/master.xml

  web:
    resources:
      cache:
        cachecontrol:
          max-age: 30d
          cache-public: true
      chain:
        strategy:
          content:
            enabled: true
            paths: "/**"

app:
  api:
    url: https://api.football-data.org/v4/
    key: ${API_KEY}

