spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: admin

#    url: jdbc:h2:mem:test
#    username: admin
#    password: admin

  liquibase:
    contexts: dev
#    clear-checksums: true